# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-19 11:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='odds',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('game', models.CharField(max_length=50)),
                ('mid', models.CharField(max_length=50)),
                ('match_name', models.CharField(max_length=50)),
                ('tournament', models.CharField(max_length=50)),
                ('odds', models.CharField(max_length=50)),
                ('datetime', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'odds',
            },
        ),
    ]
