# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-20 09:53
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('odds', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='odds',
            old_name='match_name',
            new_name='match',
        ),
        migrations.RenameField(
            model_name='odds',
            old_name='mid',
            new_name='match_id',
        ),
    ]
