# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-01-09 06:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('odds', '0002_auto_20160820_0953'),
    ]

    operations = [
        migrations.CreateModel(
            name='time',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('current', models.DateTimeField()),
            ],
        ),
        migrations.DeleteModel(
            name='odds',
        ),
    ]
