# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-01-09 06:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('odds', '0003_auto_20170109_0602'),
    ]

    operations = [
        migrations.AlterField(
            model_name='time',
            name='current',
            field=models.CharField(max_length=50),
        ),
    ]
